version: '3.3'
services:

  postgres:
    image: postgres:14
    restart: always
    environment:
      - TZ=Etc/UTC
      - POSTGRES_USER=mwallet
      - POSTGRES_PASSWORD=mwallet@001
      - POSTGRES_DB=mwallet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
